Separate config and rollout; introduce ausroller module
endocode/ausroller pull request #12
Opened 2017-01-05 12:28 UTC by mattthias

* This commit separates the code for configuration (reading cli
  parameter, reading config file) and the actual code to rollout.

2017-01-05 18:27 UTC, jmastr requested changes
Refactoring is looking. No need to import the whole Ausroller for the test case(s). Great! Please change the minor suggestion.

2017-01-05 18:27 UTC, jmastr commented on ausroller.py
> +#!/usr/bin/python
In `core.py` you take:
```
#!/usr/bin/env python2
# encoding: utf-8
```
I suggest to be consistent here

2017-01-05 18:41 UTC, mattthias commented on ausroller.py
> +#!/usr/bin/python
Good point. But the hashbang line is superflous in core.py and main() too :-D 
Will fix that

2017-01-23 15:35 UTC, mattthias commented
@jmastr  @hemarkus  Could you please review this PR again?

2017-01-24 13:01 UTC, merged