Make ausroller pip installable
endocode/ausroller pull request #19
Opened 2017-01-23 17:46 UTC by mattthias

This pr uses @hemarkus  work from https://github.com/endocode/ausroller/pull/18 to install ausroller with pip. Also changes the .travis.yml to use pip to install during tests

2017-01-23 20:16 UTC, hemarkus requested changes
Some minor changes needed

2017-01-23 20:16 UTC, hemarkus commented on ausroller/config.py
> +    def __init__(self):
Omit this method if you are not doing anything here.

2017-01-23 20:16 UTC, hemarkus commented on ausroller/config.py
> +class Configurator(object):
The name sounds wrong. This is a configuration or a context but it does not configure anything, but holds configuration values.

2017-01-23 20:16 UTC, hemarkus commented on ausroller/config.py
> +    def _custom_json_pairs_hook(self, pairs):
This is a helper function and does not use or change the instance. Therefore it should be at least a staticmethod.

2017-01-23 20:16 UTC, hemarkus commented on ausroller/config.py
> +    def read_variables(self, varfile):
This is also not worth a method. See above.

2017-01-23 20:16 UTC, hemarkus commented on ausroller/core.py
> +            app_name and resource type
This is rather useless.

2017-01-23 20:16 UTC, hemarkus commented on tests/test_configuration.py
> +                Configurator().read_variables(tempfile.name)
If the intention to make read_variable a method is to test the object construction - that is actually doing nothing see above - this should not be done implicit but with a dedicated test.

2017-01-24 12:56 UTC, mattthias commented on ausroller/config.py
> +class Configurator(object):
i renamed the class to Configuration

2017-01-24 12:56 UTC, mattthias commented on ausroller/config.py
> +    def __init__(self):
gone.

2017-01-24 12:56 UTC, mattthias commented on ausroller/core.py
> +            app_name and resource type
removed

2017-01-25 08:57 UTC, merged